export const sources = {
  filo: { title: 'Diccionario streamer · Filo News', url: 'https://www.filo.news/gaming/Diccionario-streamer-que-significan-las-expresiones-Nashe-Breo-insta-ido-Ndeah-y-de-rucula-20200720-0043.html' },
  pais: { title: 'El lenguaje que popularizó Coscu · El País', url: 'https://www.elpais.com.uy/domingo/insta-buenardo-o-de-ruta-el-lenguaje-adolescente-que-popularizo-coscu' },
  untref: { title: 'Diccionario Latinoamericano · UNTREF', url: 'https://diccionario.untref.edu.ar/buscar.php?p=nashe&q=1566' }
};
// Definitions and examples are original editorial text. A null source marks an entry to verify.
export const words = [
  { slug: 'buenardo', word: 'buenardo', syllables: 'bue · nar · do', kind: 'adjetivo', category: 'Clásicos', definition: 'Algo que está muy bueno. Un juego, un tema, una jugada o ese plan que salió mejor de lo esperado.', example: 'Este tema está buenardo, ponelo de nuevo.', note: 'Una de las expresiones más reconocibles del universo de la Army. El sufijo «-ardo» también aparece en otras palabras del chat.', source: 'filo', related: ['malardo', 'nashe', 'epicardovich'] },
  { slug: 'nashe', word: 'nashe', syllables: 'na · she', kind: 'interjección', category: 'Clásicos', definition: 'Una expresión de aprobación o entusiasmo. Se usa cuando algo está buenísimo o te sorprende para bien.', example: '¿Conseguiste entradas? Naaashe.', note: 'También vas a encontrar variantes como «nashi». Su sentido depende del tono y del contexto.', source: 'untref', related: ['buenardo', 'dou', 'nazi'] },
  { slug: 'dou', word: 'dou', syllables: 'dou', kind: 'interjección', category: 'Reacciones', definition: 'Un festejo en una sola palabra. Sale cuando una jugada, una noticia o un momento merece celebrarse.', example: '¡Ganamos la última ronda, dou!', note: 'Las vocales se pueden estirar: «douuu».', source: 'filo', related: ['nashe', 'buenardo'] },
  { slug: 'de-ruta', word: 'de ruta', syllables: 'de · ru · ta', kind: 'expresión', category: 'Expresiones', definition: 'Una forma de decir que está todo bien o acompañar algo con buena onda. Su sentido cambia con la conversación.', example: 'Sale una partida con los pibes. De ruta.', note: 'Es parte de una familia de expresiones que juega con el sonido, como «de rúcula».', source: 'pais', related: ['de-ruta-atlantica', 'de-rucula'] },
  { slug: 'epicardovich', word: 'epicardovich', syllables: 'e · pi · car · do · vich', kind: 'adjetivo', category: 'Expresiones', definition: 'Una manera exagerada y en joda de decir que algo fue épico.', example: 'Ese final fue epicardovich.', note: 'Combina «épico» con terminaciones juguetonas del chat. Entrada inicial pendiente de una fuente específica o un clip de uso.', source: null, related: ['buenardo', 'picantovich'] },
  { slug: 'ndeah', word: 'ndeah', syllables: 'nde · ah', kind: 'interjección', category: 'Reacciones', definition: 'Un remate que le da un tono de broma, ironía o exageración a lo que acabás de decir.', example: 'Mañana arranco el gimnasio a las seis. Ndeah.', note: 'Puede funcionar de manera parecida a «ahre». No tiene una única interpretación en todos los contextos.', source: 'pais', related: ['dou', 'nashe'] },
  { slug: 'malardo', word: 'malardo', syllables: 'ma · lar · do', kind: 'adjetivo', category: 'Clásicos', definition: 'Algo malo, flojo o que no estuvo a la altura.', example: 'El final de la película estuvo malardo.', note: 'Definición editorial de uso. Falta incorporar una fuente o un clip representativo.', source: null, related: ['buenardo'] },
  { slug: 'de-ruta-atlantica', word: 'de ruta atlántica', syllables: 'de · ru · ta · at · lán · ti · ca', kind: 'expresión', category: 'Expresiones', definition: 'Una extensión humorística de «de ruta». El chiste está en llevar la frase un poquito más lejos.', example: 'Terminamos todo y encima temprano. De ruta atlántica.', note: 'Propuesta inicial basada en el vocabulario aportado para este proyecto. El uso y su origen necesitan un clip o fuente de la comunidad.', source: null, related: ['de-ruta', 'de-rucula'] },
  { slug: 'de-rucula', word: 'de rúcula', syllables: 'de · rú · cu · la', kind: 'expresión', category: 'Expresiones', definition: 'Una variante en broma de «de ruta», usada para acompañar una situación con aprobación o buena onda.', example: 'Ya está todo listo para el stream. De rúcula.', note: 'El juego de palabras importa más que su significado literal.', source: 'filo', related: ['de-ruta', 'de-ruta-atlantica'] },
  { slug: 'picantovich', word: 'picantovich', syllables: 'pi · can · to · vich', kind: 'adjetivo', category: 'Expresiones', definition: 'Algo o alguien picante: intenso, atrevido o que levanta la temperatura de una conversación.', example: 'Se puso picantovich la partida.', note: 'La terminación «-ovich» agrega un tono humorístico; el significado base sigue siendo «picante».', source: 'pais', related: ['epicardovich', 'ido'] },
  { slug: 'ido', word: 'ido', syllables: 'i · do', kind: 'adjetivo', category: 'Reacciones', definition: 'Algo extraordinario, muy intenso o que se fue de lo habitual. También describe a alguien que está jugando increíble.', example: 'Cinco bajas en una ronda, estás ido.', note: 'En este uso no significa que alguien se haya retirado. El contexto de la frase marca la diferencia.', source: 'filo', related: ['buenardo', 'picantovich'] },
  { slug: 'insta', word: 'insta', syllables: 'ins · ta', kind: 'expresión', category: 'Clásicos', definition: 'Según el contexto, puede indicar que algo se hace de inmediato o servir para valorar algo positivamente.', example: 'Prendió stream, entro insta.', note: 'No siempre se refiere a Instagram. Esta entrada describe su uso en la jerga del streaming.', source: 'filo', related: ['buenardo', 'nashe'] },
  { slug: 'nazi', word: 'nazi', syllables: 'na · zi', kind: 'uso histórico', category: 'Archivo', definition: 'En una etapa de esta jerga se utilizó como una reacción de intensidad o aprobación. Es un uso polémico por el significado histórico de la palabra.', example: 'Se conserva como referencia histórica del vocabulario, sin proponer su uso.', note: 'Fuera de esa jerga designa al nazismo y a sus seguidores. La asociación con el régimen genocida motivó críticas y variantes como «nashe». Documentarlo no implica avalarlo.', source: 'filo', related: ['nashe'], sensitive: true }
];
export const normalize = (text) => text.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();
export function findWords(query = '', category = 'Todas', letter = '') {
  const q = normalize(query);
  return words.filter(w => (category === 'Todas' || w.category === category) && (!letter || normalize(w.word).startsWith(normalize(letter))) && normalize(`${w.word} ${w.definition}`).includes(q));
}
